### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by sehyunkwon** [fawazsammani/clip-interpret-mutual-knowledge#1]
Hello! Thank you for your excellent work.

I enjoyed reading your paper.

Do you have any plans to release the code?

Sincerely,
Sehyun Kwon

**Comment by fawazsammani** [comment]
Thank you for your interest in our work! 
Yes sure, I will release it within this week. Its just that it has been a busy month with conference deadlines approaching and i was not finding the time to clean the code and upload it. 

Regards

**Comment by sehyunkwon** [comment]
Thanks for your answer!
